version: '2'
services:
    managesecurity-app:
        image: managesecurity
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:sqlserver://managesecurity-mssql:1433;database=ManageSecurity
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    managesecurity-mssql:
        extends:
            file: mssql.yml
            service: managesecurity-mssql
